apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: network-sample
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1alpha1
    kind: XNetworkSample
  resources:

  - name: vpc
    base:
      apiVersion: ec2.aws.upbound.io/v1beta1
      kind: VPC
      metadata:
        labels:
          resource: "vpc"
          name: "" #patched
      spec:
        forProvider:
          region: eu-central-1
          cidrBlock: 172.16.0.0/16
    patches:
    - fromFieldPath: spec.vpcName
      toFieldPath: metadata.labels.name
