apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetworksamples.example.crossplane.io
spec:
  defaultCompositionRef:
    name: network-sample
  group: example.crossplane.io
  claimNames:
    kind: NetworkSample
    plural: networksamples
  names:
    kind: XNetworkSample
    plural: xnetworksamples
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              vpcName:
                type: string
            required:
            - vpcName
